name: ci
on:
  push:
    branches: actions-test
jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: build and publish
      run: ./latestbuild.sh
      
